services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: menu-backend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/db:/backend/data/db
      - ./data/env:/env
      - ./data/logs:/backend/data/logs
      - ./data/storage:/backend/data/storage
    environment:
      - PATH_TO_DB=/backend/data/db/db.sqlite3
      - PATH_TO_ENV=/env
      - PATH_TO_STORAGE=/backend/data/storage
      - RSA_PRIVATE_KEY=RSA_private_key.pem
      - RSA_PUBLIC_KEY=RSA_public_key.pem
      - PATH_TO_LOGS=/backend/data/logs
      - BACKEND_LOG=backend.log
    env_file:
      - .env
    ports:
      - "14536:14536"
    networks:
      - menu_network
    develop:
      watch:
        - action: rebuild
          path: ./backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: menu-frontend
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/env:/env
      - ./data/storage:/usr/share/nginx/html/storage/storage
      - ./frontend/assets:/usr/share/nginx/html/storage/assets
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT:-29157}:${FRONTEND_PORT:-29157}"
    networks:
      - menu_network
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: ./frontend

networks:
  menu_network:
    driver: bridge
