services:

  traefik:
    image: traefik:v3.5.3
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    image: laptopcoder/school-dining-room-menu-backend:latest
    container_name: menu-backend
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/db:/backend/data/db
      - ./data/env:/env
      - ./data/logs:/backend/data/logs
      - ./data/storage:/backend/data/storage
    environment:
      - PATH_TO_DB=/backend/data/db/db.sqlite3
      - PATH_TO_ENV=/env
      - PATH_TO_STORAGE=/backend/data/storage
      - RSA_PRIVATE_KEY=RSA_private_key.pem
      - RSA_PUBLIC_KEY=RSA_public_key.pem
      - PATH_TO_LOGS=/backend/data/logs
      - BACKEND_LOG=backend.log
    env_file:
      - ./backend/.env
    ports:
      - "14536:14536"

  frontend:
    image: laptopcoder/school-dining-room-menu-frontend:latest
    container_name: menu-frontend
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/env:/env
      - ./data/storage:/usr/share/nginx/html/storage/storage
      - ./frontend/assets:/usr/share/nginx/html/storage/assets
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "29157:29157"

networks:
  proxy:
    driver: bridge
